name: E5-Auto-Renewal

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'  # chạy hàng ngày lúc 8h sáng VN (1h UTC)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        env:
          E5_CLIENT_ID: ${{ secrets.E5_CLIENT_ID }}
          E5_CLIENT_SECRET: ${{ secrets.E5_CLIENT_SECRET }}
          E5_REFRESH_TOKEN: ${{ secrets.E5_REFRESH_TOKEN }}
        run: |
          python main.py
